### ISSUE TITLE
[✨ Feature] Home 마이그레이션 작업 

### ISSUE THREAD

**Issue by seochan99** [Swipe-Jeju/swiping-jeju-frontend_v2#6]
## 🛠 Issue

Home 마이그레이션 작업

## 📝 To-do

- [x] 1. Home - index page
- [x] 2. Home - Landing Component
- [x] 3. Home - Map Component
- [ ] 4. Home - KeywordInput Component
